

spring:
  application:
    name: b2
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: bootdb2user
    password: bootdb2user
    url: jdbc:mariadb://localhost:3306/bootdb2

    hikari:
      minimum-idle: 1
      maximum-pool-size: 5
      connection-timeout: 10000

logging:
  level:
    com.zaxxer: info
    org.springframework: info

mybatis:
  mapper-locations: classpath:mapper/*.xml