

spring:
  application:
    name: b2
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: malldbuser
    password: malldbuser
    url: jdbc:mariadb://localhost:3306/malldb

    hikari:
      minimum-idle: 1
      maximum-pool-size: 5
      connection-timeout: 10000
  thymeleaf:
    cache: false

logging:
  level:
    com.zaxxer: debug
    org.springframework.jdbc: debug

mybatis:
  mapper-locations: classpath:mapper/*.xml

