

spring:
  application:
    name: b2
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: malldbuser
    password: malldbuser
    url: jdbc:mariadb://localhost:3306/malldb

    hikari:
      minimum-idle: 1
      maximum-pool-size: 5
      connection-timeout: 10000
  thymeleaf:
    cache: false
  servlet:
    multipart:
      enabled: true
      location: C:\\upload
      max-file-size: 2MB
      max-request-size: 20MB


logging:
  level:
    com.zaxxer: debug
    org.springframework.jdbc: debug

mybatis:
  mapper-locations: classpath:mapper/**/*.xml


board:
  upload: D:\\upload\\attach
