

spring:
  application:
    name: b2
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: malldbuser
    password: malldbuser
    url: jdbc:mariadb://localhost:3306/malldb

    hikari:
      minimum-idle: 1
      maximum-pool-size: 5
      connection-timeout: 10000
  thymeleaf:
    cache: false
  servlet:
    multipart:
      enabled: true
      location: C:\\upload
      max-file-size: 2MB
      max-request-size: 20MB
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id:
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope: profile_nickname, account_email, profile_image
            client-name: Kakao
            client-secret:
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id


logging:
  level:
    com.zaxxer: info
    org.springframework.jdbc: info
    org:
      apache:
        ibatis: debug
      springframework:
        security: trace
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: org.zerock.b2.**.dto
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

board:
  upload: D:\\upload\\attach


